export const PERSIAN_YEAR_FORMAT = "jYYYY";
export const PERSIAN_MONTH_NAME_FORMAT = "jMMMM";
export const PERSIAN_MONTH_NUMBER_FORMAT = "jMM";
export const PERSIAN_DAY_FORMAT = "jDD";
export const PERSIAN_DAY_SHORT_FORMAT = "jD";
export const PERSIAN_FULL_TIME_FORMAT = "jYYYY/jMM/jDD HH:mm";
export const PERSIAN_FULL_DATE_FORMAT = "jYYYY/jMM/jDD";
export const PERSIAN_MONTH = "jMonth";
export const PERSIAN_YEAR = "jYear";

export const GREGORIAN_YEAR_FORMAT = "YYYY";
export const GREGORIAN_YEAR = "year";
export const GREGORIAN_MONTH_NAME_FORMAT = "MMMM";
export const GREGORIAN_DAY_SHORT_FORMAT = "D";
export const GREGORIAN_DAY_FORMAT = "DD";
export const GREGORIAN_FULL_TIME_FORMAT = "YYYY/MM/DD HH:mm";
export const GREGORIAN_FULL_DATE_FORMAT = "YYYY/MM/DD";
export const GREGORIAN_MONTH = "month";
export const GREGORIAN_MONTH_NUMBER_FORMAT = "MM";
