import { Default, SelectProps } from "./types";
declare const Select: <T extends Record<string, unknown> = Default>({
  data,
  value: propValue,
  labelExtractor,
  valueExtractor,
  onChange,
  onClear,
  disabled,
  unit,
  allowClear,
  AddonAfter,
  addonAfterClassName,
  addonAfterStyle,
  addonBefore,
  addonBeforeClassName,
  addonBeforeStyle,
  className,
  onBlur,
  onFocus,
  placeholder,
  style,
  wrapperClassName,
  wrapperStyle,
  popupClassName,
  popupStyles,
  multiple,
  onSearch,
  hasSearch,
  onMouseEnter,
  onMouseLeave,
}: SelectProps<T>) => import("react/jsx-dev-runtime").JSX.Element;
export { Select };
